ncdk = {}

require("ncdk.Fraction")

require("ncdk.NoteChart")
require("ncdk.MetaData")
require("ncdk.LayerData")
require("ncdk.LayerDataSequence")
require("ncdk.SignatureTable")
require("ncdk.TempoData")
require("ncdk.TempoDataSequence")
require("ncdk.StopData")
require("ncdk.StopDataSequence")
require("ncdk.VelocityData")
require("ncdk.VelocityDataSequence")
require("ncdk.NoteData")
require("ncdk.NoteDataSequence")
require("ncdk.TimeData")
require("ncdk.SpaceData")
require("ncdk.TimePoint")
require("ncdk.InputMode")